version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./django.Dockerfile
    container_name: azure-django
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
